apiVersion: v1
data:
  index-custom-html.conf: |
    <!DOCTYPE html>
    <html>
    <body>
    <iframe width="580" height="345" src="https://docs.harness.io/">
    </iframe>
    </body>
    </html>
kind: ConfigMap
metadata:
  name: index-cm
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: my-nginx-svc
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: my-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: "nginx:latest"
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html
          name: nginx-index-file
      volumes: 
      - name: nginx-index-file
        configMap:
          name: index-cm
          items:
          - key: index-custom-html.conf
            path: index.html
