apiVersion: v1
data:
  index.html: |
      <html>
      <h1>Welcome</h1>
      </br>
      <h1>Hi! This is a configmap Index file </h1>
      </html>
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: my-nginx-svc
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: my-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: "nginx:latest"
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html/index.html
          name: nginx-index-file
      volumes: 
      - name: nginx-index-file
        configMap:
          name: index-html-configmap
